<?php

namespace ContainerXOXGb7I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XvRkYX2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XvRkYX2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XvRkYX2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored..service_locator.XvRkYX2.App\\config\\Parameter', NULL, 'Cannot autowire service ".service_locator.XvRkYX2": it references class "App\\config\\Parameter" but no such service exists.'],
        ], [
            'post' => 'App\\config\\Parameter',
        ]);
    }
}
