<?php

namespace ContainerXOXGb7I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParameterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XvRkYX2.App\config\Parameter' shared service.
     *
     * @return \App\config\Parameter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.XvRkYX2": it references class "App\\config\\Parameter" but no such service exists.');
    }
}
