###############################################
#Application Routes
###############################################
app_home:
  path: /
  controller: App\Controller\HomeController::index
app_register:
  path: /inscription
  controller: App\Controller\RegistrationController::register
app_blog:
  path: /blog
  controller: App\Controller\BlogController::index
app_login:
  path: /connexion
  controller: App\Controller\SecurityController::login
app_logout:
  path: /deconnexion
  controller: App\Controller\SecurityController::logout
app_admin:
  path: /admin
  controller: App\Controller\BlogController::admin
app_profil:
  path: /profil
  controller: App\Controller\ProfilController::index

###############################################
#Blog Routes
###############################################
blog_add:
  path: blog/ajouter
  controller: App\Controller\BlogController::add
blog_edit:
  path: blog/edit/{id}
  controller: App\Controller\BlogController::edit
  requirements:
    id: '\d+'
blog_show:
  path: blog/show/{id}
  controller: App\Controller\BlogController::show
blog_remove:
  path: blog/remove/{id}
  controller: App\Controller\BlogController::remove
  requirements:
    id: '\d+'

###############################################
#Admin Routes
###############################################
admin_users:
  path: /admin/users
  controller: App\Controller\UserController::index
admin_user_add:
  path: /admin/user/add
  controller: App\Controller\UserController::add
admin_user_edit:
  path: /admin/user/edit/{id}
  controller: App\Controller\UserController::edit
  requirements:
    id: '\d+'
admin_user_show:
  path: /admin/user/{id}
  controller: App\Controller\UserController::show
  requirements:
    id: '\d+'
admin_user_remove:
  path: /admin/user/remove/{id}
  controller: App\Controller\UserController::remove
  requirements:
    id: '\d+'

###############################################
#User Routes
###############################################
profil_password_update:
  path: /profil/mot_de_passe/editer
  controller: App\Controller\SecurityController::editPassword

profil_remove:
  path: /profil/supprimer
  controller: App\Controller\UserController::remove

###############################################
#User Routes
###############################################
comment_valid:
  path: /admin/comment/valid/{id}
  controller: App\Controller\CommentsController::validComment
  requirements:
    id: '\d+'

comment_remove:
  path: /admin/comment/remove/{id}
  controller: App\Controller\CommentsController::removeComment
  requirements:
    id: '\d+'