home:
  path: /
  controller: App\Controller\HomeController::index
register:
  path: /inscription
  controller: App\Controller\RegistrationController::register
blog:
  path: /blog
  controller: App\Controller\BlogController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
