<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQOxtkmO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQOxtkmO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQOxtkmO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQOxtkmO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQOxtkmO\App_KernelDevDebugContainer([
    'container.build_hash' => 'QOxtkmO',
    'container.build_id' => 'd7dc480c',
    'container.build_time' => 1613498867,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQOxtkmO');
