<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8jecT5q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8jecT5q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8jecT5q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8jecT5q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8jecT5q\App_KernelDevDebugContainer([
    'container.build_hash' => '8jecT5q',
    'container.build_id' => '448f2f27',
    'container.build_time' => 1610992922,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8jecT5q');
