<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPUpWBKN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPUpWBKN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPUpWBKN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPUpWBKN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPUpWBKN\App_KernelDevDebugContainer([
    'container.build_hash' => 'PUpWBKN',
    'container.build_id' => '7fd0bfff',
    'container.build_time' => 1610963724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPUpWBKN');
